"""setting up trade_requests

Revision ID: be5416422ad0
Revises: b598e6451c09
Create Date: 2021-06-16 10:50:35.226528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5416422ad0'
down_revision = 'b598e6451c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_requests',
    sa.Column('requesting_team_id', sa.Integer(), nullable=False),
    sa.Column('recipient_team_id', sa.Integer(), nullable=False),
    sa.Column('player_sending_id', sa.Integer(), nullable=False),
    sa.Column('player_receiving_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_receiving_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_sending_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['recipient_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['requesting_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('requesting_team_id', 'recipient_team_id', 'player_sending_id', 'player_receiving_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_requests')
    # ### end Alembic commands ###
