"""leagueplayers added

Revision ID: 3c1c604625ef
Revises: fb4a96d1f69d
Create Date: 2021-06-03 13:19:19.185881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c1c604625ef'
down_revision = 'fb4a96d1f69d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_players',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('league_id', 'player_id')
    )
    op.create_index('unique_player_league', 'league_players', ['player_id', 'league_id'], unique=True)
    op.drop_constraint('player_cards_league_id_fkey', 'player_cards', type_='foreignkey')
    op.drop_column('player_cards', 'league_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_cards', sa.Column('league_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('player_cards_league_id_fkey', 'player_cards', 'leagues', ['league_id'], ['id'])
    op.drop_index('unique_player_league', table_name='league_players')
    op.drop_table('league_players')
    # ### end Alembic commands ###
