"""commented out user_id

Revision ID: 101bd7d15e89
Revises: db3be8b7a979
Create Date: 2021-06-02 22:16:36.508933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101bd7d15e89'
down_revision = 'db3be8b7a979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('player_cards_user_id_fkey', 'player_cards', type_='foreignkey')
    op.drop_constraint('player_cards_player_id_fkey', 'player_cards', type_='foreignkey')
    op.create_foreign_key(None, 'player_cards', 'players', ['player_id'], ['id'])
    op.drop_column('player_cards', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_cards', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'player_cards', type_='foreignkey')
    op.create_foreign_key('player_cards_player_id_fkey', 'player_cards', 'leagues', ['player_id'], ['id'])
    op.create_foreign_key('player_cards_user_id_fkey', 'player_cards', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
