"""added position to player model

Revision ID: 9e39811f8be8
Revises: 97ef14f1e7fc
Create Date: 2021-06-09 18:11:33.991860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e39811f8be8'
down_revision = '97ef14f1e7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('position', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'position')
    # ### end Alembic commands ###
