"""changed player model added nbateams

Revision ID: 91eb79f85db9
Revises: 9e39811f8be8
Create Date: 2021-06-10 11:39:45.160836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91eb79f85db9'
down_revision = '9e39811f8be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('nba_team', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'players', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'nba_team')
    # ### end Alembic commands ###
