"""test

Revision ID: 4ecc84cae478
Revises: b598e6451c09
Create Date: 2021-06-18 19:59:50.423508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ecc84cae478'
down_revision = 'b598e6451c09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trade_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requesting_team_id', sa.Integer(), nullable=True),
    sa.Column('recipient_team_id', sa.Integer(), nullable=True),
    sa.Column('player_sending_id', sa.Integer(), nullable=True),
    sa.Column('player_receiving_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_receiving_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['player_sending_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['recipient_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['requesting_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_requests')
    # ### end Alembic commands ###
