"""Trade_Request

Revision ID: af443e34edfa
Revises: be5416422ad0
Create Date: 2021-06-18 16:48:33.764001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af443e34edfa'
down_revision = 'be5416422ad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade_requests', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_requests', 'id')
    # ### end Alembic commands ###
