"""changed leaguemembers model

Revision ID: 2688e76d561b
Revises: 3c1c604625ef
Create Date: 2021-06-05 22:53:40.660925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2688e76d561b'
down_revision = '3c1c604625ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_user_league', 'league_members', ['user_id', 'league_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_user_league', table_name='league_members')
    # ### end Alembic commands ###
